version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend-app
    volumes:
      - ./app/dist:/usr/share/nginx/html
    ports:
      - "5173:80"